name: Static Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]
  schedule:
    - cron: "0 1 * * 1"

permissions:
  contents: read

jobs:
  static:
    uses: coreshop/workflow-collection/.github/workflows/static.yml@main